import { Colors } from "@/constants/Colors";
import { StyleSheet } from "react-native";

export const style = StyleSheet.create({
    container: {
        display: "flex",
        flex: 1,
        marginVertical: 20,
        marginHorizontal: 18,
    },
    mapView: {
        backgroundColor: Colors.cinza,
        display: 'flex',
        flexDirection: 'column',
        width: '100%',
        height: 150,
        borderRadius: 10,
        paddingHorizontal: 20,
        paddingVertical: 15,
        marginTop: 10,
        marginBottom: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 4.65,
    },
    titles: {
        fontSize: 18,
        fontFamily: 'PoppinsMedium',
    },
    cardsPView: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginVertical: 15,
    },
    cardsPequenos: {
        backgroundColor: 'white',
        justifyContent: "space-around",
        gap: 10,
        alignItems: "center",
        display: 'flex',
        flexDirection: 'row',
        width: '45%',
        height: 'auto',
        borderRadius: 10,
        padding: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 4.65,
    },
    cardView: {
        backgroundColor: 'white',
        justifyContent: "center",
        gap: 25,
        display: 'flex',
        flexDirection: 'row',
        width: '100%',
        height: 'auto',
        borderRadius: 10,
        padding: 10,
        marginTop: 10,
        marginBottom: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 4.65,
    },
    infoCard: {
        display: "flex",
        flexDirection: "column",
        width: "25%",
    },
})